export { default as Profile } from './Profile'
export { default as Cardpizza } from './CardPizza'
export { default as Footer } from './Footer'
export { default as Header } from './Header'
export { default as NotFound } from './NotFound'
export { default as ProtectedRoutes } from './ProtectedRoutes'
export { default as PublicRoutes } from './PublicRoutes'
